quickboot: Do nothing in KernelUidCpuFreqTimeReader
In quickboot mode, kernel does not support cpu /proc/uid_time_in_state.
This patch modifies KernlUidCpuFreqTimeReader class to do nothing.

Following runtime error is lost.

E KernelUidCpuFreqTimeReader: Failed to read /proc/uid_time_in_state:
java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or
directory)

Signed-off-by: Sungwoo Park <swpark@nexell.co.kr>
Change-Id: I9ffd38a92a9a63dd2b186c0df83bf00daff1a2d5
Reviewed-on: https://review.gerrithub.io/c/NexellCorp/android_platform_frameworks_base/+/466007